.TH "atadmin" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atadmin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateClass\fP ($ModID, $classStart, $classEnd, $qrMD5)"
.br
.ti -1c
.RI "\fBgetClassID\fP ($qrMD5)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "createClass ($ModID, $classStart, $classEnd, $qrMD5)"

.SS "getClassID ($qrMD5)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
