.TH "C:/wamp/www/vesey.atspace.eu/qr/tools Directory Reference" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/tools Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmerge\&.php\fP"
.br
.ti -1c
.RI "file \fBmerged_config\&.php\fP"
.br
.ti -1c
.RI "file \fBmerged_header\&.php\fP"
.br
.in -1c
