.TH "C:/wamp/www/vesey.atspace.eu/qr Directory Reference" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbindings\fP"
.br
.ti -1c
.RI "directory \fBtools\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBphpqrcode\&.php\fP"
.br
.ti -1c
.RI "file \fBqr\&.php\fP"
.br
.ti -1c
.RI "file \fBqrbitstream\&.php\fP"
.br
.ti -1c
.RI "file \fBqrconfig\&.php\fP"
.br
.ti -1c
.RI "file \fBqrconst\&.php\fP"
.br
.ti -1c
.RI "file \fBqrencode\&.php\fP"
.br
.ti -1c
.RI "file \fBqrimage\&.php\fP"
.br
.ti -1c
.RI "file \fBqrinput\&.php\fP"
.br
.ti -1c
.RI "file \fBqrlib\&.php\fP"
.br
.ti -1c
.RI "file \fBqrmask\&.php\fP"
.br
.ti -1c
.RI "file \fBqrrscode\&.php\fP"
.br
.ti -1c
.RI "file \fBqrspec\&.php\fP"
.br
.ti -1c
.RI "file \fBqrsplit\&.php\fP"
.br
.ti -1c
.RI "file \fBqrtools\&.php\fP"
.br
.in -1c
