.TH "C:/wamp/www/vesey.atspace.eu/lib Directory Reference" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/lib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcourses\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBinsertdata\&.php\fP"
.br
.ti -1c
.RI "file \fBlogin\&.php\fP"
.br
.ti -1c
.RI "file \fBshowQR\&.php\fP"
.br
.ti -1c
.RI "file \fBsloggedin\&.php\fP"
.br
.ti -1c
.RI "file \fBslogin\&.php\fP"
.br
.ti -1c
.RI "file \fBtakeattend\&.php\fP"
.br
.in -1c
