.TH "com\tecnick\tcpdf" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com\tecnick\tcpdf \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Class to create QR-code arrays for TCPDF class\&. QR Code symbol is a 2D barcode that can be scanned by handy terminals such as a mobile phone with CCD\&. The capacity of QR Code is up to 7000 digits or 4000 characters, and has high robustness\&. This class supports QR Code model 2, described in JIS (Japanese Industrial Standards) X0510:2004 or ISO/IEC 18004\&. Currently the following features are not supported: ECI and FNC1 mode, Micro QR Code, QR Code model 1, Structured mode\&.
.PP
This class is derived from 'PHP QR Code encoder' by Dominik Dzienia (http://phpqrcode.sourceforge.net/) based on 'libqrencode C library 3\&.1\&.1\&.' by Kentaro Fukuchi (http://megaui.net/fukuchi/works/qrencode/index.en.html), contains Reed-Solomon code written by Phil Karn, KA9Q\&. QR Code is registered trademark of DENSO WAVE INCORPORATED (http://www.denso-wave.com/qrcode/index-e.html)\&. Please read comments on this class source file for full copyright and license information\&.
.PP
Class for generating QR-code array for TCPDF\&. 
.PP
\fBAuthor:\fP
.RS 4
Nicola Asuni 
.RE
.PP
\fBCopyright:\fP
.RS 4
2010 Nicola Asuni - Tecnick\&.com S\&.r\&.l (www\&.tecnick\&.com) Via Della Pace, 11 - 09044 - Quartucciu (CA) - ITALY - www\&.tecnick\&.com - info@tecnick.com \fBhttp://www.gnu.org/copyleft/lesser.html LGPL  1\&.0\&.002 \fP
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
