.TH "C:/wamp/www/vesey.atspace.eu/lib/courses.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/lib/courses.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$dbAttend\fP = new \fBdb\fP()"
.br
.ti -1c
.RI "if(isset($_GET['q'])) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$dbAttend = new \fBdb\fP()"

.SS "if (isset($_GET['q'])) else"
\fBInitial value:\fP
.PP
.nf
{
  $q='1'
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
