.TH "FrameFiller" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrameFiller \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($width, &$frame)"
.br
.ti -1c
.RI "\fBsetFrameAt\fP ($at, $val)"
.br
.ti -1c
.RI "\fBgetFrameAt\fP ($at)"
.br
.ti -1c
.RI "\fBnext\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$width\fP"
.br
.ti -1c
.RI "\fB$frame\fP"
.br
.ti -1c
.RI "\fB$x\fP"
.br
.ti -1c
.RI "\fB$y\fP"
.br
.ti -1c
.RI "\fB$dir\fP"
.br
.ti -1c
.RI "\fB$bit\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($width, &$frame)"

.SH "Member Function Documentation"
.PP 
.SS "getFrameAt ($at)"

.SS "next ()"

.SS "setFrameAt ($at, $val)"

.SH "Field Documentation"
.PP 
.SS "$bit"

.SS "$dir"

.SS "$frame"

.SS "$width"

.SS "$x"

.SS "$y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
