.TH "C:/wamp/www/vesey.atspace.eu/qr/index.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/index.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$PNG_TEMP_DIR\fP = dirname(__FILE__)\&.DIRECTORY_SEPARATOR\&.'temp'\&.DIRECTORY_SEPARATOR"
.br
.ti -1c
.RI "\fB$PNG_WEB_DIR\fP = 'temp/'"
.br
.ti -1c
.RI "\fB$filename\fP = $PNG_TEMP_DIR\&.'test\&.png'"
.br
.ti -1c
.RI "\fB$errorCorrectionLevel\fP = 'L'"
.br
.ti -1c
.RI "\fB$matrixPointSize\fP = 4"
.br
.ti -1c
.RI "if(isset($_REQUEST['data'])) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$errorCorrectionLevel = 'L'"

.SS "$filename = $PNG_TEMP_DIR\&.'test\&.png'"

.SS "$matrixPointSize = 4"

.SS "$PNG_TEMP_DIR = dirname(__FILE__)\&.DIRECTORY_SEPARATOR\&.'temp'\&.DIRECTORY_SEPARATOR"

.SS "$PNG_WEB_DIR = 'temp/'"

.SS "if (isset($_REQUEST['data'])) else"
\fBInitial value:\fP
.PP
.nf
{    
    
        
        echo 'You can provide data in GET parameter: <a href='?data=like_that'>like that</a><hr/>'
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
