.TH "C:/wamp/www/vesey.atspace.eu/lib/login.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/lib/login.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBreturnheader\fP ($location)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$dbco\fP = new \fBdb\fP()"
.br
.ti -1c
.RI "if($dbco->checklogin()!=true) \fBelse\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "returnheader ($location)"

.SH "Variable Documentation"
.PP 
.SS "$dbco = new \fBdb\fP()"

.SS "if ($dbco->checklogin()!=true) else"
\fBInitial value:\fP
.PP
.nf
{
    returnheader('\&.\&./index\&.php')
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
