.TH "QRbitstream" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRbitstream \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsize\fP ()"
.br
.ti -1c
.RI "\fBallocate\fP ($setLength)"
.br
.ti -1c
.RI "\fBappend\fP (\fBQRbitstream\fP $arg)"
.br
.ti -1c
.RI "\fBappendNum\fP ($bits, $num)"
.br
.ti -1c
.RI "\fBappendBytes\fP ($\fBsize\fP, $data)"
.br
.ti -1c
.RI "\fBtoByte\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBnewFromNum\fP ($bits, $num)"
.br
.ti -1c
.RI "static \fBnewFromBytes\fP ($\fBsize\fP, $data)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$data\fP = array()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "allocate ($setLength)"

.SS "append (\fBQRbitstream\fP$arg)"

.SS "appendBytes ($size, $data)"

.SS "appendNum ($bits, $num)"

.SS "static newFromBytes ($size, $data)\fC [static]\fP"

.SS "static newFromNum ($bits, $num)\fC [static]\fP"

.SS "size ()"

.SS "toByte ()"

.SH "Field Documentation"
.PP 
.SS "$data = array()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
