.TH "C:/wamp/www/vesey.atspace.eu/qr/qrconst.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/qrconst.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBqrstr\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBQR_MODE_NUL\fP -1"
.br
.ti -1c
.RI "const \fBQR_MODE_NUM\fP 0"
.br
.ti -1c
.RI "const \fBQR_MODE_AN\fP 1"
.br
.ti -1c
.RI "const \fBQR_MODE_8\fP 2"
.br
.ti -1c
.RI "const \fBQR_MODE_KANJI\fP 3"
.br
.ti -1c
.RI "const \fBQR_MODE_STRUCTURE\fP 4"
.br
.ti -1c
.RI "const \fBQR_ECLEVEL_L\fP 0"
.br
.ti -1c
.RI "const \fBQR_ECLEVEL_M\fP 1"
.br
.ti -1c
.RI "const \fBQR_ECLEVEL_Q\fP 2"
.br
.ti -1c
.RI "const \fBQR_ECLEVEL_H\fP 3"
.br
.ti -1c
.RI "const \fBQR_FORMAT_TEXT\fP 0"
.br
.ti -1c
.RI "const \fBQR_FORMAT_PNG\fP 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const QR_ECLEVEL_H 3"

.SS "const QR_ECLEVEL_L 0"

.SS "const QR_ECLEVEL_M 1"

.SS "const QR_ECLEVEL_Q 2"

.SS "const QR_FORMAT_PNG 1"

.SS "const QR_FORMAT_TEXT 0"

.SS "const QR_MODE_8 2"

.SS "const QR_MODE_AN 1"

.SS "const QR_MODE_KANJI 3"

.SS "const QR_MODE_NUL -1"

.SS "const QR_MODE_NUM 0"

.SS "const QR_MODE_STRUCTURE 4"

.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
