.TH "C:/wamp/www/vesey.atspace.eu/qr/qrconfig.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/qrconfig.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBQR_CACHEABLE\fP true"
.br
.ti -1c
.RI "const \fBQR_CACHE_DIR\fP dirname(__FILE__)\&.DIRECTORY_SEPARATOR\&.'cache'\&.DIRECTORY_SEPARATOR"
.br
.ti -1c
.RI "const \fBQR_LOG_DIR\fP dirname(__FILE__)\&.DIRECTORY_SEPARATOR"
.br
.ti -1c
.RI "const \fBQR_FIND_BEST_MASK\fP true"
.br
.ti -1c
.RI "const \fBQR_FIND_FROM_RANDOM\fP false"
.br
.ti -1c
.RI "const \fBQR_DEFAULT_MASK\fP 2"
.br
.ti -1c
.RI "const \fBQR_PNG_MAXIMUM_SIZE\fP 1024"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const QR_CACHE_DIR dirname(__FILE__)\&.DIRECTORY_SEPARATOR\&.'cache'\&.DIRECTORY_SEPARATOR"

.SS "const QR_CACHEABLE true"

.SS "const QR_DEFAULT_MASK 2"

.SS "const QR_FIND_BEST_MASK true"

.SS "const QR_FIND_FROM_RANDOM false"

.SS "const QR_LOG_DIR dirname(__FILE__)\&.DIRECTORY_SEPARATOR"

.SS "const QR_PNG_MAXIMUM_SIZE 1024"

.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
