.TH "QRencode" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRencode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBencodeRAW\fP ($intext, $outfile=false)"
.br
.ti -1c
.RI "\fBencode\fP ($intext, $outfile=false)"
.br
.ti -1c
.RI "\fBencodePNG\fP ($intext, $outfile=false, $saveandprint=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfactory\fP ($level=\fBQR_ECLEVEL_L\fP, $size=3, $margin=4)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$casesensitive\fP = true"
.br
.ti -1c
.RI "\fB$eightbit\fP = false"
.br
.ti -1c
.RI "\fB$version\fP = 0"
.br
.ti -1c
.RI "\fB$size\fP = 3"
.br
.ti -1c
.RI "\fB$margin\fP = 4"
.br
.ti -1c
.RI "\fB$structured\fP = 0"
.br
.ti -1c
.RI "\fB$level\fP = \fBQR_ECLEVEL_L\fP"
.br
.ti -1c
.RI "\fB$hint\fP = \fBQR_MODE_8\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "encode ($intext, $outfile = \fCfalse\fP)"

.SS "encodePNG ($intext, $outfile = \fCfalse\fP, $saveandprint = \fCfalse\fP)"

.SS "encodeRAW ($intext, $outfile = \fCfalse\fP)"

.SS "static factory ($level = \fC\fBQR_ECLEVEL_L\fP\fP, $size = \fC3\fP, $margin = \fC4\fP)\fC [static]\fP"

.SH "Field Documentation"
.PP 
.SS "$casesensitive = true"

.SS "$eightbit = false"

.SS "$hint = \fBQR_MODE_8\fP"

.SS "$level = \fBQR_ECLEVEL_L\fP"

.SS "$margin = 4"

.SS "$size = 3"

.SS "$structured = 0"

.SS "$version = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
