.TH "QRimage" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRimage \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBpng\fP ($frame, $filename=false, $pixelPerPoint=4, $outerFrame=4, $saveandprint=FALSE)"
.br
.ti -1c
.RI "static \fBjpg\fP ($frame, $filename=false, $pixelPerPoint=8, $outerFrame=4, $q=85)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static jpg ($frame, $filename = \fCfalse\fP, $pixelPerPoint = \fC8\fP, $outerFrame = \fC4\fP, $q = \fC85\fP)\fC [static]\fP"

.SS "static png ($frame, $filename = \fCfalse\fP, $pixelPerPoint = \fC4\fP, $outerFrame = \fC4\fP, $saveandprint = \fCFALSE\fP)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
