.TH "C:/wamp/www/vesey.atspace.eu/qr/qrimage.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/qrimage.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBQRimage\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBQR_IMAGE\fP true"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const QR_IMAGE true"

.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
