.TH "C:/wamp/www/vesey.atspace.eu/qr/qrinput.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/qrinput.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBQRinputItem\fP"
.br
.ti -1c
.RI "class \fBQRinput\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBSTRUCTURE_HEADER_BITS\fP 20"
.br
.ti -1c
.RI "const \fBMAX_STRUCTURED_SYMBOLS\fP 16"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const MAX_STRUCTURED_SYMBOLS 16"

.SS "const STRUCTURE_HEADER_BITS 20"

.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
