.TH "QRinputItem" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRinputItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($mode, $size, $data, $bstream=null)"
.br
.ti -1c
.RI "\fBencodeModeNum\fP ($version)"
.br
.ti -1c
.RI "\fBencodeModeAn\fP ($version)"
.br
.ti -1c
.RI "\fBencodeMode8\fP ($version)"
.br
.ti -1c
.RI "\fBencodeModeKanji\fP ($version)"
.br
.ti -1c
.RI "\fBencodeModeStructure\fP ()"
.br
.ti -1c
.RI "\fBestimateBitStreamSizeOfEntry\fP ($version)"
.br
.ti -1c
.RI "\fBencodeBitStream\fP ($version)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$mode\fP"
.br
.ti -1c
.RI "\fB$size\fP"
.br
.ti -1c
.RI "\fB$data\fP"
.br
.ti -1c
.RI "\fB$bstream\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($mode, $size, $data, $bstream = \fCnull\fP)"

.SH "Member Function Documentation"
.PP 
.SS "encodeBitStream ($version)"

.SS "encodeMode8 ($version)"

.SS "encodeModeAn ($version)"

.SS "encodeModeKanji ($version)"

.SS "encodeModeNum ($version)"

.SS "encodeModeStructure ()"

.SS "estimateBitStreamSizeOfEntry ($version)"

.SH "Field Documentation"
.PP 
.SS "$bstream"

.SS "$data"

.SS "$mode"

.SS "$size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
