.TH "QRmask" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRmask \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBwriteFormatInformation\fP ($width, &$frame, $\fBmask\fP, $level)"
.br
.ti -1c
.RI "\fBmask0\fP ($x, $y)"
.br
.ti -1c
.RI "\fBmask1\fP ($x, $y)"
.br
.ti -1c
.RI "\fBmask2\fP ($x, $y)"
.br
.ti -1c
.RI "\fBmask3\fP ($x, $y)"
.br
.ti -1c
.RI "\fBmask4\fP ($x, $y)"
.br
.ti -1c
.RI "\fBmask5\fP ($x, $y)"
.br
.ti -1c
.RI "\fBmask6\fP ($x, $y)"
.br
.ti -1c
.RI "\fBmask7\fP ($x, $y)"
.br
.ti -1c
.RI "\fBmakeMaskNo\fP ($maskNo, $width, $s, &$d, $maskGenOnly=false)"
.br
.ti -1c
.RI "\fBmakeMask\fP ($width, $frame, $maskNo, $level)"
.br
.ti -1c
.RI "\fBcalcN1N3\fP ($length)"
.br
.ti -1c
.RI "\fBevaluateSymbol\fP ($width, $frame)"
.br
.ti -1c
.RI "\fBmask\fP ($width, $frame, $level)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBserial\fP ($bitFrame)"
.br
.ti -1c
.RI "static \fBunserial\fP ($code)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$runLength\fP = array()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.SH "Member Function Documentation"
.PP 
.SS "calcN1N3 ($length)"

.SS "evaluateSymbol ($width, $frame)"

.SS "makeMask ($width, $frame, $maskNo, $level)"

.SS "makeMaskNo ($maskNo, $width, $s, &$d, $maskGenOnly = \fCfalse\fP)"

.SS "mask ($width, $frame, $level)"

.SS "mask0 ($x, $y)"

.SS "mask1 ($x, $y)"

.SS "mask2 ($x, $y)"

.SS "mask3 ($x, $y)"

.SS "mask4 ($x, $y)"

.SS "mask5 ($x, $y)"

.SS "mask6 ($x, $y)"

.SS "mask7 ($x, $y)"

.SS "static serial ($bitFrame)\fC [static]\fP"

.SS "static unserial ($code)\fC [static]\fP"

.SS "writeFormatInformation ($width, &$frame, $mask, $level)"

.SH "Field Documentation"
.PP 
.SS "$runLength = array()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
