.TH "C:/wamp/www/vesey.atspace.eu/qr/qrmask.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/qrmask.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBQRmask\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBN1\fP 3"
.br
.ti -1c
.RI "const \fBN2\fP 3"
.br
.ti -1c
.RI "const \fBN3\fP 40"
.br
.ti -1c
.RI "const \fBN4\fP 10"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const N1 3"

.SS "const N2 3"

.SS "const N3 40"

.SS "const N4 10"

.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
