.TH "QRrawcode" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRrawcode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBQRinput\fP $input)"
.br
.ti -1c
.RI "\fBinit\fP (array $spec)"
.br
.ti -1c
.RI "\fBgetCode\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$version\fP"
.br
.ti -1c
.RI "\fB$datacode\fP = array()"
.br
.ti -1c
.RI "\fB$ecccode\fP = array()"
.br
.ti -1c
.RI "\fB$blocks\fP"
.br
.ti -1c
.RI "\fB$rsblocks\fP = array()"
.br
.ti -1c
.RI "\fB$count\fP"
.br
.ti -1c
.RI "\fB$dataLength\fP"
.br
.ti -1c
.RI "\fB$eccLength\fP"
.br
.ti -1c
.RI "\fB$b1\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBQRinput\fP$input)"

.SH "Member Function Documentation"
.PP 
.SS "getCode ()"

.SS "init (array$spec)"

.SH "Field Documentation"
.PP 
.SS "$b1"

.SS "$blocks"

.SS "$count"

.SS "$datacode = array()"

.SS "$dataLength"

.SS "$ecccode = array()"

.SS "$eccLength"

.SS "$rsblocks = array()"

.SS "$version"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
