.TH "QRrs" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRrs \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinit_rs\fP ($symsize, $gfpoly, $fcr, $prim, $nroots, $pad)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fB$items\fP = array()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static init_rs ($symsize, $gfpoly, $fcr, $prim, $nroots, $pad)\fC [static]\fP"

.SH "Field Documentation"
.PP 
.SS "$items = array()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
