.TH "QRrsblock" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRrsblock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($dl, $data, $el, &$ecc, \fBQRrsItem\fP $rs)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$dataLength\fP"
.br
.ti -1c
.RI "\fB$data\fP = array()"
.br
.ti -1c
.RI "\fB$eccLength\fP"
.br
.ti -1c
.RI "\fB$ecc\fP = array()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($dl, $data, $el, &$ecc, \fBQRrsItem\fP$rs)"

.SH "Field Documentation"
.PP 
.SS "$data = array()"

.SS "$dataLength"

.SS "$ecc = array()"

.SS "$eccLength"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
