.TH "QRrsItem" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRrsItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmodnn\fP ($x)"
.br
.ti -1c
.RI "\fBencode_rs_char\fP ($data, &$parity)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinit_rs_char\fP ($symsize, $gfpoly, $fcr, $prim, $nroots, $pad)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$mm\fP"
.br
.ti -1c
.RI "\fB$nn\fP"
.br
.ti -1c
.RI "\fB$alpha_to\fP = array()"
.br
.ti -1c
.RI "\fB$index_of\fP = array()"
.br
.ti -1c
.RI "\fB$genpoly\fP = array()"
.br
.ti -1c
.RI "\fB$nroots\fP"
.br
.ti -1c
.RI "\fB$fcr\fP"
.br
.ti -1c
.RI "\fB$prim\fP"
.br
.ti -1c
.RI "\fB$iprim\fP"
.br
.ti -1c
.RI "\fB$pad\fP"
.br
.ti -1c
.RI "\fB$gfpoly\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "encode_rs_char ($data, &$parity)"

.SS "static init_rs_char ($symsize, $gfpoly, $fcr, $prim, $nroots, $pad)\fC [static]\fP"

.SS "modnn ($x)"

.SH "Field Documentation"
.PP 
.SS "$alpha_to = array()"

.SS "$fcr"

.SS "$genpoly = array()"

.SS "$gfpoly"

.SS "$index_of = array()"

.SS "$iprim"

.SS "$mm"

.SS "$nn"

.SS "$nroots"

.SS "$pad"

.SS "$prim"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
