.TH "C:/wamp/www/vesey.atspace.eu/qr/qrrscode.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/qrrscode.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBQRrsItem\fP"
.br
.ti -1c
.RI "class \fBQRrs\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
