.TH "C:/wamp/www/vesey.atspace.eu/qr/qrspec.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/qr/qrspec.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBQRSPEC_VERSION_MAX\fP 40"
.br
.ti -1c
.RI "const \fBQRSPEC_WIDTH_MAX\fP 177"
.br
.ti -1c
.RI "const \fBQRCAP_WIDTH\fP 0"
.br
.ti -1c
.RI "const \fBQRCAP_WORDS\fP 1"
.br
.ti -1c
.RI "const \fBQRCAP_REMINDER\fP 2"
.br
.ti -1c
.RI "const \fBQRCAP_EC\fP 3"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const QRCAP_EC 3"

.SS "const QRCAP_REMINDER 2"

.SS "const QRCAP_WIDTH 0"

.SS "const QRCAP_WORDS 1"

.SS "const QRSPEC_VERSION_MAX 40"

.SS "const QRSPEC_WIDTH_MAX 177"

.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
