.TH "QRsplit" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRsplit \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($dataStr, $input, $modeHint)"
.br
.ti -1c
.RI "\fBidentifyMode\fP ($pos)"
.br
.ti -1c
.RI "\fBeatNum\fP ()"
.br
.ti -1c
.RI "\fBeatAn\fP ()"
.br
.ti -1c
.RI "\fBeatKanji\fP ()"
.br
.ti -1c
.RI "\fBeat8\fP ()"
.br
.ti -1c
.RI "\fBsplitString\fP ()"
.br
.ti -1c
.RI "\fBtoUpper\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBisdigitat\fP ($str, $pos)"
.br
.ti -1c
.RI "static \fBisalnumat\fP ($str, $pos)"
.br
.ti -1c
.RI "static \fBsplitStringToQRinput\fP ($string, \fBQRinput\fP $input, $modeHint, $casesensitive=true)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$dataStr\fP = ''"
.br
.ti -1c
.RI "\fB$input\fP"
.br
.ti -1c
.RI "\fB$modeHint\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($dataStr, $input, $modeHint)"

.SH "Member Function Documentation"
.PP 
.SS "eat8 ()"

.SS "eatAn ()"

.SS "eatKanji ()"

.SS "eatNum ()"

.SS "identifyMode ($pos)"

.SS "static isalnumat ($str, $pos)\fC [static]\fP"

.SS "static isdigitat ($str, $pos)\fC [static]\fP"

.SS "splitString ()"

.SS "static splitStringToQRinput ($string, \fBQRinput\fP$input, $modeHint, $casesensitive = \fCtrue\fP)\fC [static]\fP"

.SS "toUpper ()"

.SH "Field Documentation"
.PP 
.SS "$dataStr = ''"

.SS "$input"

.SS "$modeHint"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
