.TH "QRtools" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRtools \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBbinarize\fP ($frame)"
.br
.ti -1c
.RI "static \fBtcpdfBarcodeArray\fP ($code, $mode= 'QR, L', $tcPdfVersion= '4\&.5\&.037')"
.br
.ti -1c
.RI "static \fBclearCache\fP ()"
.br
.ti -1c
.RI "static \fBbuildCache\fP ()"
.br
.ti -1c
.RI "static \fBlog\fP ($outfile, $err)"
.br
.ti -1c
.RI "static \fBdumpMask\fP ($frame)"
.br
.ti -1c
.RI "static \fBmarkTime\fP ($markerId)"
.br
.ti -1c
.RI "static \fBtimeBenchmark\fP ()"
.br
.ti -1c
.RI "static \fBbinarize\fP ($frame)"
.br
.ti -1c
.RI "static \fBtcpdfBarcodeArray\fP ($code, $mode= 'QR, L', $tcPdfVersion= '4\&.5\&.037')"
.br
.ti -1c
.RI "static \fBclearCache\fP ()"
.br
.ti -1c
.RI "static \fBbuildCache\fP ()"
.br
.ti -1c
.RI "static \fBlog\fP ($outfile, $err)"
.br
.ti -1c
.RI "static \fBdumpMask\fP ($frame)"
.br
.ti -1c
.RI "static \fBmarkTime\fP ($markerId)"
.br
.ti -1c
.RI "static \fBtimeBenchmark\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static binarize ($frame)\fC [static]\fP"

.SS "static binarize ($frame)\fC [static]\fP"

.SS "static buildCache ()\fC [static]\fP"

.SS "static buildCache ()\fC [static]\fP"

.SS "static clearCache ()\fC [static]\fP"

.SS "static clearCache ()\fC [static]\fP"

.SS "static dumpMask ($frame)\fC [static]\fP"

.SS "static dumpMask ($frame)\fC [static]\fP"

.SS "static log ($outfile, $err)\fC [static]\fP"

.SS "static log ($outfile, $err)\fC [static]\fP"

.SS "static markTime ($markerId)\fC [static]\fP"

.SS "static markTime ($markerId)\fC [static]\fP"

.SS "static tcpdfBarcodeArray ($code, $mode = \fC'QR\fP, L', $tcPdfVersion = \fC'4\&.5\&.037'\fP)\fC [static]\fP"

.SS "static tcpdfBarcodeArray ($code, $mode = \fC'QR\fP, L', $tcPdfVersion = \fC'4\&.5\&.037'\fP)\fC [static]\fP"

.SS "static timeBenchmark ()\fC [static]\fP"

.SS "static timeBenchmark ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
