.TH "C:/wamp/www/vesey.atspace.eu/lib/takeattend.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/lib/takeattend.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetClassMD5\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$class\fP = \fBgetClassMD5\fP()"
.br
.ti -1c
.RI "\fB$dbatt\fP = new \fBdb\fP()"
.br
.ti -1c
.RI "\fB$username\fP = $dbatt->getUsername()"
.br
.ti -1c
.RI "\fB$password\fP = $dbatt->getPassword()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "getClassMD5 ()"

.SH "Variable Documentation"
.PP 
.SS "$class = \fBgetClassMD5\fP()"

.SS "$dbatt = new \fBdb\fP()"

.SS "$password = $dbatt->getPassword()"

.SS "$username = $dbatt->getUsername()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
