.TH "C:/wamp/www/vesey.atspace.eu/testindex.php" 3 "Sun Mar 3 2013" "Version 0.001" "Count Me In" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/vesey.atspace.eu/testindex.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$dbco\fP = new \fBdb\fP()"
.br
.ti -1c
.RI "if($dbco->checklogin()!=true) \fBelse\fP"
.br
.ti -1c
.RI "\fB$qrcode\fP = new \fBqr\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$dbco = new \fBdb\fP()"

.SS "$qrcode = new \fBqr\fP()"

.SS "if ($dbco->checklogin()!=true) else"
\fBInitial value:\fP
.PP
.nf
{
  

  
  echo '<div id='main'>You are logged in </div>'
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Count Me In from the source code\&.
